version: '3.7'
services:
  aidbox-db:
    image: "${PGIMAGE}"
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:${PGPORT}"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: "${AIDBOX_IMAGE}"
    pull_policy: always
    depends_on: ["aidbox-db"]
    links:
      - "aidbox-db:database"
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
    volumes:
      - "./:${BOX_PROJECT_GIT_TARGET__PATH}"
    env_file:
      - .env
    environment:
      PGHOST: aidbox-db
      PGPORT: "${PGPORT}"

  aidbox-healthcheck:
      image: curlimages/curl
      entrypoint: /bin/sleep 10000
      links:
        - aidbox
      depends_on:
        - aidbox
      healthcheck:
        test: "curl --fail http://aidbox:${AIDBOX_PORT}/__healthcheck || exit 1"
        interval: 2s
        timeout: 60s
        retries: 200